name: skier-check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v4
        with:
          arguments: build
          build-root-directory: app
      - name: Build and run
        run: ./gradlew build
