name: skier-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Build and test
      run: |
        ./gradlew build
        ./gradlew test
        
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        sonar-project-properties: >
          sonar.projectKey=your-project-key
          sonar.organization=your-organization
          sonar.sources=app/src/main/java
          sonar.tests=app/src/test/java
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Code Coverage Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./app/build/reports/jacoco/test/jacocoTestReport.xml
        flags: unittests
        
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./app/build/libs
